#
# Makefile for 1/5 C binaries: optimization: 0
#


CC = gcc
CFLAGS = -Wall -Wextra -O0

SRCS = src/main.c src/naive.c src/less_naive.c
HDRS = src/primes.h

OBJS = $(SRCS:.c=.o)
TARGET = build/opt0/main
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

