#
# Pin Tool Makefile - Direct compilation approach
# Matt Wolffe, James Madison University, 2025*
#

PINTOOL = prime-ultra-minimal
PIN_ROOT = /opt/pin-direct
TARGET = intel64
SRC = ../pin-tools/$(PINTOOL).cpp
OBJDIR = ../build/pin

# Simplified Pin compilation
CXX = g++-12
CXXFLAGS = -D__PIN__=1 -DPIN_CRT=1 -fno-strict-aliasing -fno-stack-protector -fno-exceptions
CXXFLAGS += -funwind-tables -fasynchronous-unwind-tables -fno-rtti -DTARGET_IA32E -DHOST_IA32E
CXXFLAGS += -fPIC -DTARGET_LINUX -O3 -fomit-frame-pointer -Wall -Wno-unknown-pragmas

# Include paths
INCLUDES = -I$(PIN_ROOT)/source/include/pin -I$(PIN_ROOT)/source/include/pin/gen
INCLUDES += -I$(PIN_ROOT)/extras/components/include -I$(PIN_ROOT)/extras/xed-intel64/include/xed
INCLUDES += -I$(PIN_ROOT)/extras/crt/include

# Libraries - simplified
LIBS = -L$(PIN_ROOT)/intel64/lib -L$(PIN_ROOT)/extras/xed-intel64/lib -lpin -lxed

$(OBJDIR)/$(PINTOOL).so: $(SRC) | $(OBJDIR)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -shared -o $@ $< $(LIBS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -rf $(OBJDIR)

.PHONY: clean
