#
# Simple (but not too simple) Makefile
# Matt Wolffe, James Madison University, 2025*
#
# (*I'm not like a prof, this is just a nod to the 
# way Dr. Lam documented his makefiles for 261)
#
# This makefile builds the C++ instrumentation binary (which I still haven't written)
# from pin-tools/prime-instrumentation.cpp
#


PINTOOL = prime-instrumentation
PIN_ROOT = /opt/pin
TARGET = intel64

SRC = ../pin_tools/$(PINTOOL).cpp
OBJDIR = ../build/pin

# TODO @mfwolffe understand this pin boilerplate lol
PIN_INCLUDE = -I$(PIN_ROOT)/source/include/pin -I$(PIN_ROOT)/source/include/pin/gen -I$(PIN_ROOT)/extras/components/include -I$(PIN_ROOT)/extras/xed-intel64/include
PIN_LIB = -L$(PIN_ROOT)/intel64/lib -L$(PIN_ROOT)/extras/xed-intel64/lib -lpin -lxed

CXX = g++
CXXFLAGS = -O3 -fomit-frame-pointer -fno-strict-aliasing -fno-rtti -fno-exceptions -Wall $(PIN_INCLUDE)

$(OBJDIR)/$(PINTOOL).so: $(SRC)
    mkdir -p $(OBJDIR)
    $(CXX) $(CXXFLAGS) -shared -o $@ $< $(PIN_LIB)

clean:
    rm -rf $(OBJDIR)

.PHONY: clean
